/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HighScore = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllHighScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, HighScore))],
      ['query'],
    ),
  'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
  'setHighScore' : IDL.Func([IDL.Nat, IDL.Int], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HighScore = IDL.Record({ 'score' : IDL.Nat, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'getAllHighScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, HighScore))],
        ['query'],
      ),
    'getHighScore' : IDL.Func([], [IDL.Nat], ['query']),
    'setHighScore' : IDL.Func([IDL.Nat, IDL.Int], [], []),
  });
};

export const init = ({ IDL }) => { return []; };